### ISSUE TITLE
can not parser domain like _acme-challenge.aaabbb.me

### ISSUE THREAD

**Issue by luluxiuxiu** [Blobfolio/adbyss#1]
The domain name \_acme-challenge.aaabbb.me cannot be used, which is mainly used for ACME to apply for a certificate，\_ is not vailed char?

**Comment by luluxiuxiu** [comment]
\_ is not vailed char?

**Comment by joshstoik1** [comment]
Thank you for opening the issue, @luluxiuxiu!

Underscores are perfectly valid in broader DNS contexts, but cannot be included in labels comprising an Internet hostname, which is what `adbyss_psl::Domain` represents. In that context, only ASCII letters, digits, and hyphens are allowed. (Unicode characters that can be encoded to ASCII with Punycode are also fine.)

I'll update the library documentation to make that distinction clearer. :wink:

**Comment by joshstoik1** [comment]
The documentation has been updated for `0.6.2`. Thanks again for raising the issue!
